stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: node:16.10-alpine
  stage: build
  only:
    - main
  before_script:
    - yarn install
  script:
    - echo "iniciando build..."
    - CI=false yarn run build
  artifacts:
    expire_in: 1 hour
    paths:
      - build
deploy:
  stage: deploy
  only:
    - main
  image: node:lts-alpine
  dependencies:
    - build
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$AWS_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "DEPLOY"
    - ssh -o StrictHostKeyChecking=no ubuntu@54.94.112.5 "cd ~/public_html && rm -rf static/"
    - scp -r -o StrictHostKeyChecking=no build/* ubuntu@54.94.112.5:~/public_html
    - ssh -o StrictHostKeyChecking=no ubuntu@54.94.112.5 "sudo docker run  -v ~/public_html:/usr/share/nginx/html:ro -p 80:80 nginx"

#funciona por favor